name: Data Sync Pipeline

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:  # Manual trigger option

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # First debug step to check raw secrets
    - name: Debug raw secrets
      run: |
        echo "MONGO_URI exists: ${{ secrets.MONGO_URI != '' }}"
        echo "PASSWORD exists: ${{ secrets.PASSWORD != '' }}"
        echo "MOTHERDUCK_TOKEN exists: ${{ secrets.MOTHERDUCK_TOKEN != '' }}"
        
    # Set environment variables properly
    - name: Set environment variables
      run: |
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV
        echo "MOTHERDUCK_TOKEN=${{ secrets.MOTHERDUCK_TOKEN }}" >> $GITHUB_ENV
        echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
        
    # Second debug step to check environment variables
    - name: Debug environment
      run: |
        echo "MONGO_URI length: ${#MONGO_URI}"
        echo "PASSWORD length: ${#PASSWORD}"
        echo "MOTHERDUCK_TOKEN length: ${#MOTHERDUCK_TOKEN}"
        
    - name: Run sync script
      run: |
        python main.py
        ls -la
        
    - name: Show log file
      run: |
        if [ -f "sync_log.txt" ]; then
          cat sync_log.txt
        else
          echo "No log file found!"
        fi
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git status
        git diff --cached --quiet || git commit -m "Auto-sync data $(date)"
        
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main