name: Data Sync Pipeline

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run sync script
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
      run: |
        echo "Current directory: $(pwd)"
        python main.py
        echo "Script exit code: $?"
        
    - name: Show log output
      run: |
        echo "=== sync_log.txt ==="
        cat sync_log.txt || echo "No log file found"
        echo "==================="
        
    - name: Setup git config
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Commit and push changes
      run: |
        git add .
        git status
        if ! git diff-index --quiet HEAD --; then
          git commit -m "Auto-sync: $(date +'%Y-%m-%d %H:%M:%S')"
          git push
        else
          echo "No changes to commit"
        fi
        
    - name: Upload logs as artifact
      uses: actions/upload-artifact@v3
      with:
        name: sync-logs
        path: |
          sync_log.txt
        if-no-files-found: warn