name: Data Sync Pipeline

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Set environment variables in a separate step
    - name: Set environment variables
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        PASSWORD: ${{ secrets.PASSWORD }}
        MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
      run: |
        echo "MONGO_URI=${MONGO_URI}" >> $GITHUB_ENV
        echo "PASSWORD=${PASSWORD}" >> $GITHUB_ENV
        echo "MOTHERDUCK_TOKEN=${MOTHERDUCK_TOKEN}" >> $GITHUB_ENV
        echo "Variables set successfully"

    # Debug step to verify variables
    - name: Verify environment variables
      run: |
        echo "MONGO_URI length: ${#MONGO_URI}"
        echo "PASSWORD length: ${#PASSWORD}"
        echo "MOTHERDUCK_TOKEN length: ${#MOTHERDUCK_TOKEN}"
        
    - name: Run sync script
      run: |
        python main.py
        ls -la
        
    - name: Show log file
      run: |
        if [ -f "sync_log.txt" ]; then
          cat sync_log.txt
        else
          echo "No log file found!"
        fi
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git status
        git diff --cached --quiet || git commit -m "Auto-sync data $(date)"
        
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main